### PR TITLE
Fixed bukkit dependency

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
What. Why?!

**Comment by Morphan1** [comment]
There's no real reason to do this. You'd still have to manually get CraftBukkit, so getting Bukkit isn't a problem whatsoever. (This assuming you're building all locally and you're not extremely lazy. If you are lazy, you shouldn't even be messing with the code and building custom builds :smile_cat:)

**Comment by sgdc3** [comment]
Your build server can't compile the project without this...

**Comment by sgdc3** [comment]
http://ci.citizensnpcs.co/job/Citizens2/1229/console

**Comment by Morphan1** [comment]
@sgdc3 if you noticed, ALL the dependencies failed, including the Citizens API. Not to mention you're basically saying that every C2 built since 1.8 came out has worked via magic.

**Comment by sgdc3** [comment]
Sorry but I'm not understanding what you are saying, I've only noticed the error in the builder's console and I know the latest 1.8 source is only avariable on spigot's maven repo.

**Comment by sgdc3** [comment]
1.8 jars aren't here: http://repo.bukkit.org/content/groups/public/org/bukkit/bukkit/

**Comment by mcmonkey4eva** [comment]
@sgdc3 We have a functional build server, that build output was a one-time glitch on the build server's end... the build ran for 18 hours because apparently it had been lost somehow, and when we aborted it, it chose to gave that error at half-random. Everything builds fine.

1.8 Bukkit is on Spigot's server yes... but CraftBukkit is not. There's no point in linking to a new repo server just to get Bukkit without getting CraftBukkit.

**Comment by sgdc3** [comment]
Ok, sorry i have misread the console log  ;)

**Pull request closed without merging**
