### PR TITLE
Add option to have players purchase items only once

### PR DESCRIPTION
**Pull request by BreadcrumbIsTaken**
## Add option to buy an item once

Adds new options to the Item Edit inventory GUI to set whether or not a player can only buy the item once and to set a message if the player's already bought it.

Requested by [Fasty](https://discord.com/channels/315163488085475337/1123370966869876767)

###### Let me know if there's anything I should add/remove :D

### CODE REVIEW

**Comment by fullwall** [comment]
Finally had time to check this sorry. It looks good, I just wonder if the purchasableOnce should be an integer? And maybe the item that has been limited should be marked as such somehow (I guess in the lore?)

**Comment by BreadcrumbIsTaken** [comment]
> Finally had time to check this sorry. It looks good, I just wonder if the purchasableOnce should be an integer? And maybe the item that has been limited should be marked as such somehow (I guess in the lore?)

Got it. I like the idea of adding the lore. Also, quick question, when you say `purchasableOnce` should be an integer, do you mean that instead of just having an option to purchase once, there should be an option to change the amount of times it can be bought? Like instead of just having it be purchased only once the user can make the item purchasable twice or thrice or 17 times for example?

**Comment by fullwall** [comment]
> > Finally had time to check this sorry. It looks good, I just wonder if the purchasableOnce should be an integer? And maybe the item that has been limited should be marked as such somehow (I guess in the lore?)
> 
> Got it. I like the idea of adding the lore. Also, quick question, when you say `purchasableOnce` should be an integer, do you mean that instead of just having an option to purchase once, there should be an option to change the amount of times it can be bought? Like instead of just having it be purchased only once the user can make the item purchasable twice or thrice or 17 times for example?

Yeah that's right - I guess it doesn't hurt that much to make it work like that even if it's niche.

**Comment by BreadcrumbIsTaken** [comment]
Done. Thanks again for the help with the previous commit fullwall :D

**Comment by fullwall** [comment]
Great! Thanks

**Pull request merged**
