### PR TITLE
`npc hologram margintop/marginbottom` command

### PR DESCRIPTION
**Pull request by BreadcrumbIsTaken**
### Usage:
`/npc hologram margintop [line #] [margin]`
`/npc hologram marginbottom [line #] [margin]`

### Adds
- `setMargin(int idx, String type, double margin)` method to set the margin of the line.

### Changes:
- Changed hologram text persist data. Text is now stored in `lines.<index>.text` and margins are stored in `lines.<index>.margin.<type>`. If an NPC's storage uses `lines.<index>` to store the text, then it will still be read as text and margins will be set to `0.0` and then on save be converted to the new format.

###### Notes:
- I was a bit confused with the `args` and `argsLength` things, so if I got the values incorrect (I did test and they worked, but just in case, ya know?) let me know :)
- If you want me to change the margins to be a variable in the class and use `@Persist` instead of saving and loading it manually, let me know and I'll try to figure it out ;)

### CODE REVIEW

**Comment by fullwall** [comment]
I think it's fine for now to not change the persistence. Looks pretty much how I would have done it! I just wondered why the direction help was changed to top/bottom?

**Comment by fullwall** [comment]
Maybe it's better to have the arguments as `margintop` and `marginbottom` for autocomplete?

**Comment by BreadcrumbIsTaken** [comment]
> I think it's fine for now to not change the persistence. Looks pretty much how I would have done it! I just wondered why the direction help was changed to top/bottom? 

Oh sorry haha that was an accident. I'll change it back.

**Comment by BreadcrumbIsTaken** [comment]
> Maybe it's better to have the arguments as `margintop` and `marginbottom` for autocomplete?

Yeah, that works for me. I'll do that instead.

**Comment by BreadcrumbIsTaken** [comment]
Both are done 👍

**Pull request merged**
