### PR TITLE
Fix no knock back on player NPC's when hit

### PR DESCRIPTION
**Pull request by JCThePants**
Player NPC's do not get knocked back when hit.

The attacking players `EntityPlayer` object checks if the entity is a player and if so, sets the entities `velocityChanged` field to false, resets the velocity values and sends a packet to the client instead.

This fix sets the `velocityChanged` field to false to prevent the velocity from being reset, waits until after the check is done and sets the `velocityChanged` value back to `true`.

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
Great work once again! @fullwall ?

**Comment by JCThePants** [comment]
Thanks =)

**Comment by mcmonkey4eva** [comment]
Erm... merge conflict from your own previous PR :/

**Comment by JCThePants** [comment]
I hope I did that right.

**Comment by mcmonkey4eva** [comment]
It looks like you're now trying to re-merge commits the main repo already has 0.o
Maybe it'd be easier to just close this PR and remake it?

**Comment by JCThePants** [comment]
Welp. This ones ruined.

**Pull request closed without merging**
