### PR TITLE
Improve tablist removal and skin updating

### PR DESCRIPTION
**Pull request by Morphan1**
From my testing, this rids the server of invisible/skinless NPCs

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
What happens if the player joins then quits immediately?

**Comment by mcmonkey4eva** [comment]
Also aren't there util functions for some of what you're doing (EG, sending tablist packet)?

**Comment by Morphan1** [comment]
@mcmonkey4eva there's a util function to send tablist stuff to all players, but not any for one specific player.. I added NMS.sendPacket() where it make sense though

**Comment by mcmonkey4eva** [comment]
> Create NPC with skin
> Reconnect
Image
Was this supposed to fix that situation?

**Pull request merged**
