### PR TITLE
Added script to automatically install all craftbukkit dependencies with BuildTools

### PR DESCRIPTION
**Pull request by Turpster**
Added script to automatically install all craftbukkit dependencies in systems Maven directory for ease-of-development using BuildTools

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
This strongly does not belong in the repo at all. As a helpful reference link to a gist that gets posted around, maybe. In the actual repo? No.

**Comment by mcmonkey4eva** [comment]
As a side note, @Turpster  we've noticed you've submitted several very low quality and rather inane PRs to a variety of GitHub repos recently, such as:
- https://github.com/graywolf336/CasinoSlots/pull/99/files which is active nonsense / completely wrong, in a PR to a repo that hasn't been touched in 2 years.
- https://github.com/niccholaspage/Fe/pull/83/files which is a questionable sane-at-all PR to a repo that hasn't been touched in **6 years**
- https://github.com/NoCheatPlus/NoCheatPlus/pull/53 which is again outright wrong and regardless is only even attempting to be a minor formatting change.

I'd like to encourage you to take significantly more time when working on PRs, including the initial stage of determining whether a PR even makes sense or is necessary. Many problems are better resolved by an issue post rather than a PR, and many problems aren't actually problems in the repo at all, and are rather confusion on your own end. PRs are generally considered to be a serious and deeply involved thing, and a series of low-effort PRs in a short time period can be seen by many as spam.

**Comment by Turpster** [comment]
@mcmonkey4eva, your first point was spot-on. I don't understand where you are coming from with your second and third points along with closing the PR.

- https://github.com/niccholaspage/Fe/pull/83/files Yes, the repository hasn't been touched in **6 years** but where are you coming from? From a stance like mine, I am trying to get an old server up and running again and I couldn't see an issue with updating a repository to 1.8 to easily be compiled (and allowing it to be ran from 1.8>), no harm in making a PR along-side that?
- https://github.com/NoCheatPlus/NoCheatPlus/pull/53 Your critique is way to harsh to the point where it's not helpful. The issue I encountered here was that it was an old repository, but if you were critiquing my code, your exaggerating terms such as _outright wrong_ and _minor_ are even more flat-out crazy when you consider that this PR allows the repo to be compiled.

Also, the point of open-source repositories is to allow your repository to easily be compiled by
1. Anyone wishing to use the plugin through compilation.
2. And **more importantly**, anyone wishing to easily develop your plugin.

**Comment by fullwall** [comment]
Let’s not have a debate about your other PRs here. This PR is not suited for Citizens because we don’t have setup scripts in the repo right now.

**Pull request closed without merging**
