### PR TITLE
Fix no knock back on player NPC's when hit

### PR DESCRIPTION
**Pull request by JCThePants**
Attempt number 2 due to my git noob mistakes.

### CODE REVIEW

**Comment by fullwall** [comment]
I don't think this will compile - there is no velocityChanged variable defined in your code.

**Comment by fullwall** [comment]
You also need to respect the protected metadata for the NPC.

**Comment by mcmonkey4eva** [comment]
velocityChanged is from entity.java -> http://git.mcmonkey.org/mcmonkey/mc-dev/blob/master/net/minecraft/server/Entity.java#L70

**Comment by fullwall** [comment]
Not sure if this will be called if the protected metadata is set, so it might be good to go. But check it anyway.

**Comment by JCThePants** [comment]
This only affects the NPC if its not protected. Checked again just to be safe.

**Pull request merged**
