### PR TITLE
Optimize lag with PlayerUpdateTask, completely safe

### PR DESCRIPTION
**Pull request by SladeHazard**
image

To: 

image

It's completely thread safe

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
- If you're using paper timings instead of a profiler (like Spark), your timing data is too inaccurate to be of developmental value.
- This code change is likely to run *slower* not faster. ConcurrentHashMap is just HashMap with extra locking checks, so that's slower... CopyOnWriteArrayList is just like ArrayList but it does more memory copies, which again is slower.

I can't decipher what the theory behind this was meant to be at all

**Comment by SladeHazard** [comment]
> * If you're using paper timings instead of a profiler (like Spark), your timing data is too inaccurate to be of developmental value.
> * This code change is likely to run _slower_ not faster. ConcurrentHashMap is just HashMap with extra locking checks, so that's slower... CopyOnWriteArrayList is just like ArrayList but it does more memory copies, which again is slower.
> 
> I can't decipher what the theory behind this was meant to be at all

here is the spark report if you're wondering: https://spark.lucko.me/oYsacAOXVA

I'll try to come up with a different approach

**Comment by ArefyNetwork** [comment]
I'm having same issue, there's an option on citizens config to avoid that PlayerUpdateTask lag?

**Comment by fullwall** [comment]
There's no lag in the spark report.

**Pull request closed without merging**
