### PR TITLE
Fix memory leak with advancements

### PR DESCRIPTION
**Pull request by Brokkonaut**
Should fix https://github.com/CitizensDev/Citizens2/issues/1272

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
Why does it only clear advancements on `die()`?

**Comment by Brokkonaut** [comment]
`die()` is called when the player is removed from the world (in `World.removeEntry()`). This happens when the entity dies or the chunk or world there the entity is is unloaded. afaik this catches all cases.

**Comment by mcmonkey4eva** [comment]
Just to confirm:
The issue is because advancements clump up after an NPC is reloaded in the world (removed and respawned)? And so the solution is to prevent doubling up?

**Comment by Brokkonaut** [comment]
Yes, every time the NPC is removed (mostly when the chunk where the NPC is gets unloaded) the AdvancementDataPlayer in the CriterionTriggers was not removed - and when the chunk is loaded again a new AdvancementDataPlayer was added there

**Comment by mcmonkey4eva** [comment]
Sounds reasonable.
Fullwall's been a bit busy, and I defer to him for pull-request-pulling bar emergency levels of inactivity.
Might be a bit before he pulls this :/
I sent him a link just to be sure he'll see it whenever he's able to come online.

**Comment by fullwall** [comment]
Thanks, appreciated!

**Pull request merged**
