### PR TITLE
fix: attribute issues

### LINKED ISSUE #3192: NPC attribute issues
### `/version` output

```txt
This server is running Paper version 1.21.3-77-master@1e035f3 (2024-12-01T15:52:35Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are 2 version(s) behind
```

### `/version Citizens` output

```txt
Citizens version 2.0.36-SNAPSHOT (build 3642)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/128674

### config.yml

https://paste.denizenscript.com/View/128675

### saves.yml

https://paste.denizenscript.com/View/128676

### Profiler report

_No response_

### Description

When setting invalid attributes (as in attributes with invalid keys) on NPCs using /npc attribute, it returns an error, but still gets APPLIED and SAVED as "null". These "null"-key attributes cause errors on startup and load/reload, as well as prevent the adding of new attributes, even if they're valid.

### PR DESCRIPTION
**Pull request by SNWCreations**
fix #3192
TODOs inside, discussion required.

### CODE REVIEW

**Comment by SNWCreations** [comment]
fix worked, TODOs need discussion.

**Comment by fullwall** [comment]
Better to add some validation logic to loading rather than erroring at spawn time

**Comment by fullwall** [comment]
Do you need me to create the translation key for you?

**Comment by SNWCreations** [comment]
> Better to add some validation logic to loading rather than erroring at spawn time

validating what? null values are excluded by this PR, did you mean values should be larger than zero?

Translation keys for invalid arguments are really needed.

**Comment by fullwall** [comment]
```
if(key == null)
```
This should be validated before onSpawn(), whether that's after loading or on setAttributeValue

**Comment by SNWCreations** [comment]
> ```
> if(key == null)
> ```
> 
> This should be validated before onSpawn(), whether that's after loading or on setAttributeValue

I see. Changing it.

**Comment by fullwall** [comment]
No, if you add load(DataKey key) method it will be called in trait class

**Comment by SNWCreations** [comment]
> No, if you add load(DataKey key) method it will be called in trait class

Oh that's good, but should we fix this in API instead of there? Will it be possible to deserialize another somewhat Map with Attribute as key type?

**Comment by SNWCreations** [comment]
> No, if you add load(DataKey key) method it will be called in trait class

Followed this, ready for review.

**Pull request merged**
