### PR TITLE
Update to 1.8.4/5

### PR DESCRIPTION
**Pull request by sanjay900**
There wasn't a huge amount changed, except for a couple of nms functions being deobsuficated.

### CODE REVIEW

**Comment by sanjay900** [comment]
I haven't done a huge amount of testing, but it seems pretty stable.

**Comment by mcmonkey4eva** [comment]
You entirely recommitted several files.

**Comment by Morphan1** [comment]
Was this tested thoroughly? Sometimes NMS methods will change, but have the same parameters and return type, which is very troublesome sometimes.

**Comment by sanjay900** [comment]
I have no idea why some files decided to completly recommit themselves

**Comment by sanjay900** [comment]
What needs to be tested? Npcs seem to work fine, no errors.

**Comment by sanjay900** [comment]
I tested paths and they work too

**Comment by sanjay900** [comment]
MD_5 also says on his twitter that there weren't many changes, but there was just an NMS bump. The only changes i found were a few functions and enums were deobsufcated.

**Comment by sanjay900** [comment]
I went through and checked the rest of the fields in NMS.java for deobfuscation, and the rest were fine..

**Comment by sanjay900** [comment]
I updated to 1.8.5. No NMS function definitions were changed however, so it was just a case of changing 1.8.4 to 1.8.5

**Comment by sanjay900** [comment]
I clicked the wrong button

**Comment by CKGAR** [comment]
Is there any way you could upload the compiled build to dropbox or simar and link it? That would be a huge help. Thanks!!

**Comment by CKGAR** [comment]
Except the build failed........

**Comment by mcmonkey4eva** [comment]
Patience. I'll update it to 1.8.6 then fix the build, no worries.

**Pull request merged**
