### PR TITLE
Allow custom skins for players

### PR DESCRIPTION
**Pull request by Dablakbandit**
Allow custom skins for players works for traits by setting the skin onSpawn

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
What?
Why?
Is any of this tested?
The formatting is a bit off...

**Comment by Dablakbandit** [comment]
This allows for old Property's to be used, eg if a player changes their skin this can use the players old one as long as you have the correct texture url and signature.
Sorry about formatting can be correcting if you show exactly is off

**Comment by Dablakbandit** [comment]
I required this for my custom server and yes i can confirm it works, Was the only way I could use old skins for npcs, by using a trait all I had to do was:

	public void onSpawn(){
		if(skin != null && npc.getEntity() != null){
			try{
				Object entity = PacketUtils.getHandle(npc.getEntity());
				SkinnableEntity se = (SkinnableEntity)entity;
				Property pt = skin.getSkin().getProperty();
				se.getSkinTracker().setSkin(new CustomSkin("custom_skin", UUID.fromString("49e28098-6627-483e-8f4b-73d67e5f7c89"), pt));
			}catch(Exception e){
				e.printStackTrace();
			}
		}
	}

**Comment by HurricanKai** [comment]
Pretty Old but just saw this!

Hope i can help a bit.

> as long as you have the correct texture url and signature.

But if the Skin is uploaded to Minecraft.net, The Skin will most likely be removed after some time. Also, you are supposed to use `new SkinPacketTracker(SkinabbleEntity)` instead of getSkinTracker(). (i think)
Also, you shoud update the Skin after its changed. Basicaly, you are Pushing all the Handling Functions aside, and just set all values. Which will Definatly throw a lot of errors with other Modifications. it may work in your enviorment, but is definatly not a good implementation. also `this.hasFetched = true;` is telling the System youve fetched, even if you dont. you are removing every single Handler out of the Flow. btw, Calling npc.getEntity() twice is very inefficent and unsecure. You shoud get the Entity once and work from there.

Resume:
this maybe will work, but has many Leaks in it. Just from what i tell.

(As i wanna mention again, im not an active dev here, and not even a good java dev, (im C# mostly) but as C# is close to java, and im maintaing the Blacksmith plugin, i know some of the Code. and can understand most of the Source.)

**Comment by Midnight9746** [comment]
If I'm understanding this correctly, you're wanting to save a players skin on an npc?

*Sorry I'm late, but I too just saw this*

You need to select the npc and type /npc skin -p <Desired player name>

This will save a snapshot of the current skin of the player's name you had used as well as display on the npc.

The skin will continue to stay on the npc until you do the command again to change it. It won't update when the player changes.

I had to do it when some of my npcs lost their cool looks since the account holder of the username I used changed the skin.

If you're wanting to make it so the npc has a name but a different skin, the command does the same thing.

Like say I have one called 'Today's News' and did /npc skin -p Paperboy, Today's News will look like whatever skin paperboy has (idk just an example) and keep that skin, useful since the name 'Today's News" has a ' and a space, thus the skin you're gonna normally get is a Steve or Alex.

You can change your own skin as many times as you wish but you have to wait a moment for citizens to recognize that you changed.

It's really not possible to save skins as you go unless they are saved in the default names skin thing. 

(I remember seeing in the config something like 'Clown' and it had a clown skin, and there was a way where you can assign that to the npc) 

I'm not sure if that's predefined or if it's customizable.

**Comment by Dablakbandit** [comment]
Sorry forgot to respond to this, I am trying to create npcs with an old skin (which is possible using this) . Get your skin url and store it. then change it, but you can still apply the old one as mojang doesn't clear old skins, just changes the url to a new texture.

**Comment by mcmonkey4eva** [comment]
You can change that data directly from SkinnableEntity calls

**Pull request closed without merging**
