### PR TITLE
Fixed despawned npc respawning when chunk load

### PR DESCRIPTION
**Pull request by milkyway0308**
Fixed despawned npc respawning when chunk load.
Cause of IntelliJ import manage, github detect commit to file replacement.

See NPC#despawn and EventListen#respawnAllFromCoord to see fixes.

### CODE REVIEW

**Comment by fullwall** [comment]
1. You didn't register your trait with the CitizensTraitFactory
2. The default behaviour is to respawn NPCs on chunk load: can you clarify why you want to change this?

**Comment by fullwall** [comment]
Also: we have the Spawned trait

**Comment by milkyway0308** [comment]
Checked; Didn't know Spawn trait exists

I think to make not spawn when chunk load. 
I found entity spawn when chunk loaded when despawn and load entity, and get nerveous, and  added stack trace cause no description on spawn.

Need to add description to docs. or make not loaded when despawn cause is not chunk load

**Comment by fullwall** [comment]
If the chunk unloads the entity will despawn and respawn when the chunk loads. What do you want to change about this and why?

**Comment by milkyway0308** [comment]
On chunk load, **All of NPC** respawns without checking reason.
When addon develop, it can cause error.

Need to check despawn reason if plugin called when despawning do remove entity from world.
I think destroy npc cannot be answer of this problem.

**Comment by fullwall** [comment]
https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/EventListen.java#L195
only put in respawn map when ChunkUnloadEvent is called
https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/EventListen.java#L420
prevents respawn if DespawnReason.PLUGIN used

**Comment by fullwall** [comment]
Can you describe your plugin code sequence please?

**Comment by milkyway0308** [comment]
I used this code in add-on.

`    @Override
    public void execute(ExecutedScriptData esd) {
        for (NPC npc : esd.getNPCs()) {
            npc.despawn(DespawnReason.PLUGIN);
            if (npc.getEntity() != null) {
                npc.getEntity().remove();
                Bukkit.getConsoleSender().sendMessage("§cRe-removed entity " + npc.getEntity().getName());
            }
        }
    }`

And I used this code to debug.

`    @EventHandler
    public void ev(NPCSpawnEvent e) {
        System.out.println("NPC Spawn: " + e.getNPC().getName() + ", " + e.isCancelled());
        Thread.dumpStack();
    }
`

NPC despawned successfully, but NPC respawns when chunk loaded.
Here is stack trace.

`[10:56:23] [Server thread/WARN]: java.lang.Exception: Stack trace
[10:56:23] [Server thread/WARN]: 	at java.lang.Thread.dumpStack(Thread.java:1336)
[10:56:23] [Server thread/WARN]: 	at skywolf46.nim.listener.CitizenListener.ev(CitizenListener.java:88)
[10:56:23] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
[10:56:23] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:56:23] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:56:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315)
[10:56:23] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[10:56:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[10:56:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[10:56:23] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:282)
[10:56:23] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.spawn(EventListen.java:716)
[10:56:23] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:686)
[10:56:23] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[10:56:23] [Server thread/WARN]: 	at net.citizensnpcs.EventListen$1.run(EventListen.java:155)
[10:56:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81)
[10:56:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[10:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059)
[10:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349)
[10:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007)
[10:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846)
[10:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[10:56:23] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)`

**Comment by milkyway0308** [comment]
Add, I found Citizen NPC despawn typed before Debug called. 
Uploading additional stack trace here.

[10:56:22] [Server thread/INFO]: NPC Spawn: Bridge_Exchange_Entity_18, false
[10:56:22] [Server thread/WARN]: java.lang.Exception: Stack trace
[10:56:22] [Server thread/WARN]:        at java.lang.Thread.dumpStack(Thread.java:1336)
[10:56:22] [Server thread/WARN]:        at skywolf46.nim.listener.CitizenListener.ev(CitizenListener.java:88)
[10:56:22] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:56:22] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:56:22] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:56:22] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[10:56:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315)
[10:56:22] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[10:56:22] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[10:56:22] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[10:56:22] [Server thread/WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:285)
[10:56:22] [Server thread/WARN]:        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:164)
[10:56:22] [Server thread/WARN]:        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[10:56:22] [Server thread/WARN]:        at net.citizensnpcs.Citizens$3.run(Citizens.java:339)
[10:56:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81)
[10:56:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[10:56:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059)
[10:56:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349)
[10:56:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007)
[10:56:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846)
[10:56:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)

**Comment by fullwall** [comment]
Hmm, I wonder if you despawning the NPC causes the chunk to unload?

**Comment by milkyway0308** [comment]
Re-removing entity is just my fault..
I tried that cause NPC is not disappering, and found after log npc is respawning.

I tried NPC teleport on loaded chunk, and think this is appering NPC entered on unloaded chunk.
Maybe chunk loaded and npc teleported, and npc despawned made it.

**Comment by fullwall** [comment]
One of NPCNeedsRespawnEvent, ChunkUnloadEvent, or WorldUnloadEvent may be happening. Can you figure out which one?

**Comment by milkyway0308** [comment]
ChunkUnload is most likely on this situation.

**Comment by fullwall** [comment]
Yes but I would like a thread stack of which of those three events is happening so I can track down which part of despawn logic is affecting this.

**Comment by fullwall** [comment]
Also Citizens debug output is helpful I think

**Comment by milkyway0308** [comment]
Wait please, need 15 minutes to get debug.

**Comment by milkyway0308** [comment]
Debug complete, 4 of NPC not despawned(respawned).

[20:26:17] [Server thread/INFO]: Despawned 36 DespawnReason.PLUGIN
[20:26:18] [Server thread/INFO]: Preventing further respawns of 35 due to DespawnReason.PLUGIN
[20:26:18] [Server thread/INFO]: Despawned 35 DespawnReason.PLUGIN
[20:26:18] [Server thread/INFO]: Preventing further respawns of 34 due to DespawnReason.PLUGIN
[20:26:18] [Server thread/INFO]: Despawned 34 DespawnReason.PLUGIN
[20:26:19] [Server thread/INFO]: Spawned 116 SpawnReason.PLUGIN
[20:26:19] [Server thread/INFO]: Tried to despawn 53 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 52 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 51 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 50 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 49 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 48 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 47 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 46 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 45 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 44 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 43 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 42 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 40 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 39 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 38 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 36 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 35 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 34 while already despawned.
[20:26:19] [Server thread/INFO]: Preventing further respawns of 33 due to DespawnReason.PLUGIN
[20:26:19] [Server thread/INFO]: Despawned 33 DespawnReason.PLUGIN

**Comment by fullwall** [comment]
Where is the spawns?

**Comment by milkyway0308** [comment]
Log is too large to find, I'm finding now

**Comment by milkyway0308** [comment]
Found, I despawned entity with plugin, and it work once. After I join, it respawned with chunks.

[20:24:46] [Server thread/INFO]: Spawned 53 SpawnReason.PLUGIN
[20:24:46] [Server thread/INFO]: Spawned 52 SpawnReason.PLUGIN
[20:24:46] [Server thread/INFO]: Spawned 51 SpawnReason.PLUGIN
[20:24:46] [Server thread/INFO]: Spawned 50 SpawnReason.PLUGIN
~~~ Another NPC despawning log~~~
[20:26:19] [Server thread/INFO]: Tried to despawn 53 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 52 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 51 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 50 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 49 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 48 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 47 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 46 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 45 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 44 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 43 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 42 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 40 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 39 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 38 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 36 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 35 while already despawned.
[20:26:19] [Server thread/INFO]: Tried to despawn 34 while already despawned.
[20:26:19] [Server thread/INFO]: Preventing further respawns of 33 due to DespawnReason.PLUGIN
[20:26:19] [Server thread/INFO]: Despawned 33 DespawnReason.PLUGIN
[20:26:38] [User Authenticator #2/INFO]: UUID of player skywolf46 is 72e5e5fb-7f8b-337b-be56-5143e7927a11
[20:26:38] [Server thread/INFO]: skywolf46[/127.0.0.1:2891] logged in with entity id 15940 at ([world]-558.3455226021018, 30.1264258620871, -236.70537048195473)
[20:26:41] [Server thread/INFO]: Spawned 53 SpawnReason.CHUNK_LOAD
[20:26:41] [Server thread/INFO]: Spawned id 53 during org.bukkit.event.world.ChunkLoadEvent@4957a4af at [-35,-27]
[20:26:41] [Server thread/INFO]: Spawned 52 SpawnReason.CHUNK_LOAD
[20:26:41] [Server thread/INFO]: Spawned id 52 during org.bukkit.event.world.ChunkLoadEvent@4957a4af at [-35,-27]
[20:26:41] [Server thread/INFO]: Spawned 51 SpawnReason.CHUNK_LOAD
[20:26:41] [Server thread/INFO]: Spawned id 51 during org.bukkit.event.world.ChunkLoadEvent@4957a4af at [-35,-27]
[20:26:41] [Server thread/INFO]: Spawned 50 SpawnReason.CHUNK_LOAD
[20:26:41] [Server thread/INFO]: Spawned id 50 during org.bukkit.event.world.ChunkLoadEvent@4957a4af at [-35,-27]

**Comment by fullwall** [comment]
What do you mean? Is it from your plugin or Citizens bug?

**Comment by milkyway0308** [comment]
Citizen bug, or mistake.
After PLUGIN despawn, it prevents from first chunk load.
But it not prevents from second chunk load.

**Comment by fullwall** [comment]
Can't reproduce with a single NPC on my server. Need you to isolate the specific debug.

**Comment by milkyway0308** [comment]
This bug showed when spawn entity called twice.
This will disappear persistence value of despawn value.
Committed code will work, tested on 1.16.3, 1.12.2

**Comment by fullwall** [comment]
https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/npc/CitizensNPC.java#L233

**Comment by fullwall** [comment]
I tried using /npc spawn and /npc despawn (with manual plugin reason) and didn't encounter this bug.

**Comment by milkyway0308** [comment]
Cannot perform bug with that, command use filtering.
                } else if (respawn.isSpawned()) {
                    throw new CommandException("citizens.commands.npc.spawn.already-spawned", new Object[]{respawn.getName()});
                }

At test enviroment, unload chunk and load chunk was worked, and removed from map.
Next chunk load, cause npc is not map, npc spawned from chunk load.

**Comment by fullwall** [comment]
I don't understand because NPCDespawnEvent should prevent respawns from chunk loads https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/EventListen.java#L420

Are you saying that the NPC is respawning during npc.despawn? If so, can you provide a stack trace of which line causes the chunk to load again?

**Comment by milkyway0308** [comment]
Can I contact to you?
I can't describe it more, I did my best on my comments.
Maybe seeing bug directly is best decision on now.

**Comment by fullwall** [comment]
Yes

**Pull request closed without merging**
